SELECT * FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_TBL_MEMBER_NO';

CREATE SEQUENCE SEQ_TBL_MEMBER_NO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

alter table;

select *
    from tbl_member;
    
delete  
   from tbl_member;
   
  commit;
  
  select *
    from TBL_E_CONTRACT_HISTORY;
    
    
    CREATE TABLE TBL_E_CONTRACT_HISTORY (
    HISTORY_NO NUMBER PRIMARY KEY,
    CONTRACT_NO VARCHAR2(20) NOT NULL,
    SENDER_MEMBER_NO VARCHAR2(20) NOT NULL,
    RECIPIENT_EMAIL VARCHAR2(100) NOT NULL,
    ACTION_TYPE VARCHAR2(20) NOT NULL,  -- 'SENT', 'VIEWED', 'SIGNED' 등
    ACTION_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_ECH_CONTRACT FOREIGN KEY (CONTRACT_NO) REFERENCES TBL_CONTRACT(CONTRACT_NO)
);

CREATE SEQUENCE SEQ_E_CONTRACT_HISTORY_NO;

COMMENT ON TABLE TBL_E_CONTRACT_HISTORY IS '전자계약 발송 및 서명 이력';
COMMENT ON COLUMN TBL_E_CONTRACT_HISTORY.ACTION_TYPE IS '행동 유형 (SENT: 발송, VIEWED: 확인, SIGNED: 서명)';

-- 계약 상태 변경 이력 관리 테이블
CREATE TABLE TBL_CONTRACT_HISTORY (
    CONTRACT_HISTORY_NO         NUMBER              CONSTRAINT PK_CONTRACT_HISTORY PRIMARY KEY,
    CONTRACT_NO                 VARCHAR2(20)        NOT NULL,
    MEMBER_NO                   VARCHAR2(20)        NOT NULL,
    CONTRACT_HISTORY_CONTENT    VARCHAR2(1000)      NULL,
    CONTRACT_HISTORY_DATE       DATE                DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT FK_HISTORY_CONTRACT FOREIGN KEY (CONTRACT_NO) REFERENCES TBL_CONTRACT(CONTRACT_NO),
    CONSTRAINT FK_HISTORY_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES TBL_MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN TBL_CONTRACT_HISTORY.CONTRACT_HISTORY_NO IS '계약 변경 이력 고유 번호 (PK)';
COMMENT ON COLUMN TBL_CONTRACT_HISTORY.CONTRACT_NO IS '계약 고유 번호 (FK)';
COMMENT ON COLUMN TBL_CONTRACT_HISTORY.MEMBER_NO IS '변경을 수행한 회원 번호 (FK)';
COMMENT ON COLUMN TBL_CONTRACT_HISTORY.CONTRACT_HISTORY_CONTENT IS '변경 내용(사유)';
COMMENT ON COLUMN TBL_CONTRACT_HISTORY.CONTRACT_HISTORY_DATE IS '변경 일시';

--------------------------------------------------------------------------------

-- 계약 상태 변경 이력 관리 시퀀스
CREATE SEQUENCE SEQ_CONTRACT_HISTORY_NO
START WITH 1
INCREMENT BY 1;