SELECT * FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_TBL_MEMBER_NO';

CREATE SEQUENCE SEQ_TBL_MEMBER_NO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

alter table;

select *
    from tbl_member;
    
delete  
   from tbl_member;
   
  commit;
  
  select *
    from TBL_E_CONTRACT_HISTORY;
    
    
    CREATE TABLE TBL_E_CONTRACT_HISTORY (
    HISTORY_NO NUMBER PRIMARY KEY,
    CONTRACT_NO VARCHAR2(20) NOT NULL,
    SENDER_MEMBER_NO VARCHAR2(20) NOT NULL,
    RECIPIENT_EMAIL VARCHAR2(100) NOT NULL,
    ACTION_TYPE VARCHAR2(20) NOT NULL,  -- 'SENT', 'VIEWED', 'SIGNED' 등
    ACTION_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_ECH_CONTRACT FOREIGN KEY (CONTRACT_NO) REFERENCES TBL_CONTRACT(CONTRACT_NO)
);

CREATE SEQUENCE SEQ_E_CONTRACT_HISTORY_NO;

COMMENT ON TABLE TBL_E_CONTRACT_HISTORY IS '전자계약 발송 및 서명 이력';
COMMENT ON COLUMN TBL_E_CONTRACT_HISTORY.ACTION_TYPE IS '행동 유형 (SENT: 발송, VIEWED: 확인, SIGNED: 서명)';